### ISSUE TITLE
Remove sensitive information from git logs

### ISSUE THREAD

**Issue by bethouxa** [edgarFerlando/student-portal-natives#1]
Hello, I've noticed you removed a couple private keys and other sensitive info from your projects, but they still show up in the commits and they still show up in GitHub searches (try searching for "BEGIN PGP PRIVATE KEY"). I recommend you read about [git-filter-branch](https://git-scm.com/docs/git-filter-branch) and [its uses](https://stackoverflow.com/questions/872565/remove-sensitive-files-and-their-commits-from-git-history#872700) so you can also remove them from your project git log.

Also, you should invalidate the old keys because there's no telling how many people fetched them, but there are people looking for passwords and private keys on github, that's for sure. Consider the keys you used on this project compromised. 

Stay safe ;)

**Comment by edgarFerlando** [comment]
thankyou @bethouxa . . 

if you dont remind me this, i never gonna find out about this...
thanks a lot . . cheers . .;)

**Comment by FendiJatmiko** [comment]
thankyou so much @bethouxa ... :+1:
